spring:
  application:
    name: springboot-thymeleaf
  h2:
    console:
      enabled: true
      path: /h2-console
      #settings.trace: false
      #settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:springboot-thymeleaf?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    # url: jdbc:h2:mem:springboot-thymeleaf
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
logging:
  level:
    web: DEBUG
#    org.hibernate:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
server:
  port: 9090
  servlet:
    context-path: /springboot-thymeleaf